### ISSUE TITLE
Build - Nuget publish failing

### ISSUE THREAD

**Issue by mzorec** [loanstreet-usa/servicing-api-client-csharp#22]
I've noticed in dependecy graph of FlubuCore that you started using it. I've checked the build script and noticed that the build is failing with:

>  Running program '/usr/bin/dotnet':(work.dir='',args=' nuget push packages/LoanStreet.LoanServicing.0.0.0.nupkg --api-key ####')
> 
> error: Source parameter was not specified.

This  is because `--source` argument is missing in `nuget push ` command. I've noticed that the same mistake is in Flubu examples so I've decided to open an issue here :) Anyway you can fix this issue by adding  ` .ServerUrl("https://www.nuget.org/api/v2/package")` to the NugetPush task

```C#
     var nugetPush = context.CreateTarget("nuget.publish")
                .SetDescription("Publishes nuget package.")
                .AddCoreTask(x => x.NugetPush(
                        Path.Combine(PackagesFolder, NugetPackageName(context)))
                    .ServerUrl("https://www.nuget.org/api/v2/package")
                    .ApiKey(NuGetAPIKey)
                )
                .DependsOn(package);
```

**Comment by carlosarias1992** [comment]
@mzorec you're totally right! Will open a PR to solve this issue. Thank you for bringing this up to our attention.
